Weekly table only some html & UsersData JSON
Neil0696/deskeando pull request #2
Opened 2022-01-19 13:43 UTC by socrateskld

2022-01-19 15:00 UTC, gregdyke requested changes
add yarn.lock to the .gitignore file

2022-01-19 15:00 UTC, gregdyke commented on client/src/App.js
> +
you could restore this file to its previous state:

git checkout main -- client/src/App.js

2022-01-19 15:00 UTC, gregdyke commented on client/src/index.js
> +
same, no need to have these changes

2022-01-19 15:00 UTC, gregdyke commented on client/src/Data/UsersData.json
> +[
I would actually not put this in a json file, and I would call it bookings.json. But as we are going to be removing it anyway soon (and doing fetch from /api/bookings instead), it doesn't matter

2022-01-26 18:27 UTC, socrateskld commented
All the required changes are already merged , so im close this PR.

2022-01-26 18:27 UTC, closed without merging