Benjamin/delete button(cancel booking)
Neil0696/deskeando pull request #34
Opened 2022-02-05 16:57 UTC by Benjamin-GitHub

ModalCancelBookingScreen created.

2022-02-06 18:45 UTC, Benjamin-GitHub commented
There were some conflict, I did rebase my branch and now everrything seems fine. Also I checked factionality of App on my local machine

2022-02-08 17:41 UTC, gregdyke requested changes, later dismissed
The PR still needs fixing/rebasing, otherwise everything looks great

2022-02-08 17:41 UTC, gregdyke commented on client/src/pages/ModalCancelBookingScreen.js
> +				"content-type": "application/jason",
application/json, not jason :)

2022-02-08 19:48 UTC, Benjamin-GitHub commented on client/src/pages/ModalCancelBookingScreen.js
> +				"content-type": "application/jason",
Yeah! I see. Thanks

2022-02-08 19:48 UTC, kosenchiha approved these changes

2022-02-08 19:49 UTC, merged